mqtt:
  client:
    protocol: 4      # MQTTv311
  connection:
    #host localhost
    host: 10.0.2.15
    port: 1883
    keepalive: 60
  private_path: device/001
#serializer: msgpack:dumps
#deserializer: msgpack:loads
serializer: json:dumps
deserializer: json:loads
bridge:
  # ping pong
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: std_msgs.msg:Bool
    topic_from: /ping
    topic_to: ping
  - factory: mqtt_bridge.bridge:MqttToRosBridge
    msg_type: std_msgs.msg:Bool
    topic_from: ping
    topic_to: /pong
  # testTopic back
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: std_msgs.msg:String
    topic_from: /testTopic
    topic_to: testTopic
  - factory: mqtt_bridge.bridge:MqttToRosBridge
    msg_type: std_msgs.msg:String
    topic_from: echo
    topic_to: /back
  # cancelTopic back
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: std_msgs.msg:String
    topic_from: /cancelTopic
    topic_to: cancelTopic
  - factory: mqtt_bridge.bridge:MqttToRosBridge
    msg_type: std_msgs.msg:String
    topic_from: echo
    topic_to: /back
#rostopic pub /testTopic -> MQTT på topic "testTopic"
#MQTT client.publish("echo", "{"data":"string"}" (skal kobles sammen med '"')
#kommer ind i ROS på rostopic /back
